sudo: required

services:
  - docker

before_install:
  - docker build -t adibaulia/tbnfess:1.0 -f Dockerfile .

script:
  - docker images adibaulia/tbnfess:1.0

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push adibaulia/tbnfess:1.0
